apps/course/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', view_courses, name='index'),
    url(r'^nuevo/$', create_course, name='create'),
    url(r'^all$', get_courses, name='all'), #only POST
    url(r'^(?P<course_id_char>\w+)/$', show_course, name='show'),
    url(r'^(?P<course_id_char>\w+)/agregar-estudiantes$', add_students, name='add_students'), #Only POST
    url(r'^(?P<course_id>\d+)/download-template$', download_template, name='download_csv'),
    url(r'^editar/(?P<course_id_char>\w+)/$', edit_course, name='edit'),
    url(r'^borrar/(?P<course_id_char>\w+)$', delete_course, name='delete'),
    url(r'^borrar_estudiante/(?P<course_id_char>\w+)/(?P<student_rut>[\w-]+)$', delete_student, name='delete_student')
]

apps/play/urls.py
from django.conf.urls import url

from apps.play.views import *

urlpatterns = [
    url(r'^$', view_plays, name='index'),
    url(r'^stop$', stop_play, name='stop'), #Only POST
    url(r'^(?P<play_id_char>\w+)/$', show_play, name='show'),
    url(r'^(?P<play_id_char>\w+)/reply/(?P<question_id>\d+)/$', reply_play, name='reply'),
    url(r'^(?P<play_id_char>\w+)/dashboard/$', play_result, name='result'),
    url(r'^(?P<play_id_char>\w+)/download-excel$', download_excel, name='excel'),
]

#(?P<question_id>\d+)/

play/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.views.generic import TemplateView

from apps.login.urls import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include ('apps.login.urls', namespace='login')),
	url(r'^', include ('apps.teacher.urls', namespace='teacher')),
    url(r'^', include ('apps.student.urls', namespace='student')),
    url(r'^curso/', include('apps.course.urls', namespace='course')),
    url(r'^formativa/', include('apps.formative.urls', namespace='formative')),  
    url(r'^pregunta/', include('apps.question.urls', namespace='question')),
    url(r'^play/', include('apps.play.urls', namespace='play'))
]

apps/course/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    id_char = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=20)
    semester = models.CharField(max_length=10)
    year = models.CharField(max_length=4)
    description = models.CharField(max_length=200, blank=True)
    creation_date = models.DateTimeField()
    teacher = models.ForeignKey('teacher.Teacher', models.DO_NOTHING)
    student = models.ManyToManyField('student.Student', through='CourseHasStudent')

    class Meta:
        managed = False
        db_table = 'course'
        ordering = ('-creation_date',)


class CourseHasStudent(models.Model):
    course = models.ForeignKey('Course', models.DO_NOTHING)
    student = models.ForeignKey('student.Student', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'course_has_student'
        unique_together = (('course', 'student'),)

apps/course/forms.py
from django import forms

from .models import Course

class CourseForm(forms.ModelForm):
    """docstring for CourseForm"""
    class Meta:
        model = Course
        fields = ('name', 'code', 'semester', 'description')
        widgets = {
            'name': forms.TextInput(attrs={'class':'validate', 'length': 50, 'data-length': 50, 'placeholder': 'Ejemplo: Matemática Aplicada'}),
            'code': forms.TextInput(attrs={'class':'validate', 'length': 20, 'data-length': 20, 'placeholder': 'Ejemplo: MAT200'}),
            'semester': forms.Select(choices=(('1', 'I Semestre',),('2', 'II Semestre',))),
            'description': forms.Textarea(attrs={'class':'materialize-textarea validate', 'length': 200, 'data-length': 200, 'placeholder': 'Tips: Puede escribir las características pedagógicas del curso actual. Sus objetivos y como conseguirlos.'}),
        }

apps/course/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from datetime import date
import csv, os, xlrd

from play.settings import BASE_DIR
from django.contrib.auth.models import User, Group
from .forms import CourseForm
from .models import Course, CourseHasStudent
from apps.student.models import Student
from apps.play.models import Play
from itertools import chain

@login_required
def view_courses(request):
    #courses = Course.objects.all()
    courses = Course.objects.filter(
        teacher=request.user.teacher)#.order_by('id').reverse()
    return render(request, 'course/index.html', {'courses': courses})


@login_required
def show_course(request, course_id_char):
    course = Course.objects.get(id_char=course_id_char)
    students = course.student.all().order_by('user__last_name')
    plays = Play.objects.filter(course=course)
    return render(
        request,
        'course/show.html',
        {'course': course, 'students': students, 'plays': plays})


@login_required
def create_course(request):
    if request.method == "POST":
        form = CourseForm(request.POST)        
        if form.is_valid():
            course = form.save(commit=False)
            course.teacher = request.user.teacher
            course.year = date.today().year
            course.creation_date = timezone.now()
            course.id_char = "{0}{1}{2}".format(
                remove_accent(course.name.replace(" ", "")[:4].upper()),
                course.year,
                course.semester)
            course.save()
            course.id_char = "{0}{1}{2}".format(
                course.id_char,
                course.id,
                request.user.teacher.user_id)
            course.save()
            return redirect('course:show', course_id_char=course.id_char)
    else:
        form = CourseForm()
    return render(request, 'course/create.html', {'form': form, 'title': 'Crear Curso'})


@login_required
def edit_course(request, course_id_char):
    course = Course.objects.get(id_char=course_id_char)
    if request.method == 'GET':
        form = CourseForm(instance=course)
    else:
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
        return redirect('course:index')
    return render(request, 'course/create.html', {'form': form, 'title': 'MAs Play - Editar Curso'})


@login_required
def delete_course(request, course_id_char):
    try:
      course = Course.objects.get(id_char=course_id_char)
      course.delete()
      messages.add_message(request, messages.SUCCESS, course.code + ' ' + course.name + ' borrado exitosamente.')
      return redirect('course:index')
    except:
      messages.add_message(request, messages.ERROR, course.code + ' ' + course.name + ' no pudo ser borrado porque tiene estudiantes asignados. Por favor borra los estudiantes e intentalo nuevamente.')
      return redirect('course:index')

@login_required
def add_students(request, course_id_char):
    course = Course.objects.get(id_char=course_id_char)
    course_id = course.id
    if request.method == 'POST':
        data = {}
        if request.FILES:
            csvfile = request.FILES['csv_file']
            
            fout = open(BASE_DIR+'/templates/course/{0}.xls'.format(course_id), 'wb')
            for chunk in csvfile.chunks():
                fout.write(chunk)
            fout.close() 

            book = xlrd.open_workbook(BASE_DIR+'/templates/course/{0}.xls'.format(course_id))
            sh = book.sheet_by_index(0)
            for rx in range(1, sh.nrows):
                rx_rut = sh.row(rx)[0].value.strip(" ").lstrip("0").upper()           
                if Student.objects.filter(rut=rx_rut):
                    #Account exist
                    student = Student.objects.get(rut=rx_rut)                
                    try:
                        #In this course
                        CourseHasStudent.objects.get(course=course, student=student)
                    except Exception as e:
                        #Havent this course
                        m = CourseHasStudent(course=course, student=student)
                        m.save()
                        data[student.user.id] = {'rut': student.rut, 'name': student.user.first_name,
                                                'last_name': student.user.last_name}
                else:
                    #New student                    
                    rx_last_name = sh.row(rx)[1].value.strip(" ").title()
                    rx_first_name = sh.row(rx)[2].value.strip(" ").title()
                    rx_email = sh.row(rx)[3].value.strip(" ")
                    rx_study = sh.row(rx)[4].value.strip(" ").title()
                    
                    user = User.objects.create_user(
                        username=rx_rut,
                        password=rx_rut,
                        first_name=rx_first_name,
                        last_name=rx_last_name)
                    user.save()
                    student = Student.objects.create(
                        user=user,
                        rut=rx_rut,
                        study=rx_study)

                    group = Group.objects.get(name='Students')
                    user.groups.add(group)
                    user.save()

                    m = CourseHasStudent(course=course, student=student)
                    m.save()
                    data[student.user.id] = {'rut': student.rut, 'name': student.user.first_name,
                                        'last_name': student.user.last_name}
                student = None
                m = None
            
            os.remove(BASE_DIR+'/templates/course/{0}.xls'.format(course_id))            
        else:            
            for i in request.POST.lists():
                if Student.objects.filter(rut=i[1][0].upper()):
                    student = Student.objects.get(rut=i[1][0].upper())
                    #print("Existe entre todos los estudiantes")
                    try:
                        CourseHasStudent.objects.get(course=course, student=student)
                        #print("Existe en el curso")
                    except Exception as e:
                        #print("No existe en el curso")
                        m = CourseHasStudent(course=course, student=student)
                        m.save()
                        data[student.user.id] = {'rut': student.rut, 'name': student.user.first_name,
                                            'last_name': student.user.last_name}
                else:
                    #print("Nuevo")
                    user = User.objects.create_user(
                        username=i[1][0].upper(),
                        password=i[1][0].upper(),
                        first_name=i[1][1],
                        last_name=i[1][2])
                    user.save()

                    student = Student.objects.create(
                        user=user,
                        rut=i[1][0].upper())

                    group = Group.objects.get(name='Students')
                    user.groups.add(group)
                    user.save()

                    m = CourseHasStudent(course=course, student=student)
                    m.save()
                    data[student.user.id] = {'rut': student.rut, 'name': student.user.first_name,
                                        'last_name': student.user.last_name}
                student = None
                m = None
    return JsonResponse(data)

@login_required
def delete_student(request, course_id_char, student_rut):
  try:
    course = Course.objects.get(id_char=course_id_char)
    student = Student.objects.get(rut=student_rut)
    studentInCourse = CourseHasStudent.objects.get(course=course , student=student)
    studentInCourse.delete()
    return redirect('course:show', course_id_char=course_id_char)
  except Exception as e:
    messages.add_message(request, messages.ERROR, str(e))
    return redirect('course:show', course_id_char=course_id_char)


@login_required
def download_template(request, course_id):
    if request.method == "GET":
        course = Course.objects.get(id=course_id)

        #response = HttpResponse(content_type='text/csv')
        #response['Content-Disposition'] = 'attachment; filename="EstudiantesCurso-{0}.csv"'.format(course.code)

        #writer = csv.writer(response)
        #writer.writerow(['RUT', 'NOMBRES', 'APELLIDOS', 'EMAIL'])

        xls = open(BASE_DIR+"/templates/course/StudentsTemplate.xls", "rb")

        response = HttpResponse(xls, content_type="application/vnd.ms-excel")
        response["content-Disposition"] = "attachment; filename=EstudiantesCurso-{0}.xls".format(course.code)

        xls.close()

        return response

@login_required
def get_courses(request):    
    if request.method == "POST":
        #print("POST") year=date.today().year
        #print([date.today().year,date.today().year-1])
        data = {}
        last_courses = Course.objects.filter(teacher=request.user.teacher, year=date.today().year-1).order_by('id').reverse() 
        present_courses = Course.objects.filter(teacher=request.user.teacher, year=date.today().year).order_by('id').reverse()
        courses = list(chain(last_courses, present_courses))
        #print (courses)
        for course in courses:
            data[course.id] = {"code": course.code, "name": course.name}

        return JsonResponse(data)


import unicodedata
def remove_accent(string):
   return ''.join((string for string in unicodedata.normalize('NFD', string) if unicodedata.category(string) != 'Mn'))

templates/course/create.html
{% extends 'teacher/base.html' %}

{% block extracss %}
{% endblock %}

{% block extrajs %}
{% endblock %}

{% block title %}
  {% if form.name.value != None %}
    FAMA - Editar Curso
  {% else %}
    FAMA - Nuevo Curso
  {% endif %}
{% endblock %}

{% block page-title %}
  {% if form.name.value != None %}
    Editar Curso {{ form.name.value }}
  {% else %}
    Nuevo Curso
  {% endif %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12">
    <form id="for-new-course" method="POST" class="card-box col s12 m8 l8 offset-m2 offset-l2">
      {% csrf_token %}
      <div class="row last-row">
        <div class="input-field col s12">
          {{ form.name }}
          <label for="{{ form.name.id_for_label }}">Nombre del Curso</label>
          {{ form.name.errors }}
        </div>        
      </div>
      <div class="row last-row">
        <div class="input-field col s12 m6">
          {{ form.code }}
          <label for="{{ form.code.id_for_label }}">C&oacute;digo del Curso</label>
        </div>
        <div class="input-field col s12 m6">
          {{ form.semester }}
          <label for="{{ form.semester.id_for_label }}">Semestre</label>
        </div>        
      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.description }}
          <label for="{{ form.description.id_for_label }}">Descripción del curso (Opcional)</label>
        </div>
      </div>
      <div class="row right-align">
        <button class="btn waves-effect waves-light" type="submit">
          Guardar
          <i class="fa fa-send right"></i>
        </button>
      </div>  
    </form>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
<script>
  $(document).ready(function() {
    $('#nav-mobile ul.collapsible li#new_course').addClass('active').parent().parent().show().parent().addClass('active')    
    $('select').material_select();
    $('textarea').characterCounter();
  });
</script>
{% endblock %}

templates/course/index.html
{% extends 'teacher/base.html' %}
{% load staticfiles %} 

{% block extracss %}
<style type="text/css">
  .clickable-row {
    cursor: pointer;
  }
</style>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/course.delete.js' %}"></script>
{% endblock %}

{% block title %} FAMA - Mis Cursos {% endblock %}

{% block page-title %} Mis Cursos {% endblock %}

{% block content %}
<div class="row">
  <div class="col s12">
    <div style="overflow-x: auto;">
      <table class="bordered card-box">
        <thead>
          <tr>
            <th data-field="code" style="width: 120px;">C&oacute;digo</th>
            <th data-field="name" style="min-width: 200px;">Nombre</th>
            <th data-field="semester" style="width: 110px;">
              Semestre/A&ntilde;o
            </th>
            <th class="center-align" style="width: 150px;" data-field="edit">
              Acciones
            </th>
          </tr>
        </thead>
        <tbody>
          {% for course in courses %}
          <tr>
            <td>{{ course.code }}</td>
            <td>{{ course.name | truncatewords_html:5 }}</td>
            <td class="center-align">
              {{ course.semester }}/{{ course.year }}
            </td>
            <td class="center-align">
              <a class="waves-effect waves-light btn btn-action" href="{% url 'course:show' course.id_char %}">
                <i class="fa fa-info"></i>
              </a>
              <a class="waves-effect waves-light btn btn-action" href="{% url 'course:edit' course.id_char %}">
                <i class="fa fa-pencil"></i>
              </a>
              <a class="waves-effect red btn btn-action" href="{% url 'course:delete' course.id_char %}">
                <i class="fa fa-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
<script>
  $('.modal').modal();
  $(document).ready(function() {
    $("a.btn").parents('td').css("padding-bottom", "0").css("padding-top", "0");
    $('#nav-mobile ul.collapsible li#list_courses').addClass('active').parent().parent().show().parent().addClass('active');

    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });

    {% if messages %}
    {% for message in messages %}
      Materialize.toast('{{message}}', 5000, 'rounded');
    {% endfor %}
    {% endif %}
  });
</script>
{% endblock %}

templates/course/show.html
{% extends 'teacher/base.html' %}
{%load staticfiles %}

{% block extracss %}
<style type="text/css">
  .modal {
    width: 75% !important;
  }
</style>
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'js/library/js.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/course.show.js' %}"></script>
{% endblock %}

{% block title %}
FAMA - {{course.name}}
{% endblock %}

{% block page-title %}
{{course.name}}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12 m12 l6">
    <ul class="collection with-header">
      <li class="collection-header valign-wrapper">
        <div class="left-align col s6">
          <h5>Historial</h5>
        </div>
        <div class="valign right-align col s6">
          <a href="{% url 'play:index' %}" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Ver todas">
            <i class="fa fa-list fa-2x black-text"></i>
          </a>
          <a href="{% url 'formative:create' %}" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Nueva">
            <i class="fa fa-plus-square fa-2x black-text" style="padding-left: 10px;"></i>
          </a>
        </div>
      </li>
      {% if plays %}
      {% for play in plays %}
      <li class="collection-item col s12">
        <div class="s12">
          <div class="col s9 list-group">
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-file-o" aria-hidden="true"></i>&nbsp;{{play.formative.name}}
            </div>
            <div class="s12 l4 list-group-item truncate">
              &nbsp;{{play.formative.description}}
            </div>
          </div>
          <div class="col s3 right-align">
            <a class="waves-effect waves-light btn btn-action" href="{% url 'play:result' play.id_char %}">
              <i class="fa fa-bar-chart fa-2x" aria-hidden="true"></i>
            </a>
          </div>
        </div>
        <div class="col s4 m4 list-group-item">
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;{{ play.duration_to_time }}
        </div>
        <div class="col s8 m4 list-group-item">
          <i class="fa fa-calendar-times-o" aria-hidden="true"></i>&nbsp;{{ play.close_play|date:"D d/M/Y" }}
        </div>
      </li>
      {% endfor %}
      {% else %}
      <a class="collection-item center-align col s12" href="{% url 'formative:create' %}">
        <b>Comenzar primera evaluación del curso</b>
      </a>
      {% endif %}
    </ul>
  </div>

  <div class="col s12 m12 l6">
    <ul class="collection with-header">
      <li class="collection-header valign-wrapper">
        <div class="left-align col s8">
          <h5>Estudiantes</h5>
        </div>
        <div class="valign right-align col s6">
          <a href="#add_student" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Agregar estudiantes">
            <i class="fa fa-plus-square fa-2x black-text"></i>
          </a>
        </div>
      </li>
      <li class="collection-item center-align">
        <span>Estudiantes inscritos:
          <span id="student_count" data-count='{{ students.count }}'>{{ students.count }}</span>
        </span>
      </li>
      <div id="list_students" style="max-height: 400px; overflow-y: auto;">
        {% if students %}
        {% for student in students %}
        <li class="collection-item col s12">
          <div class="s12">
            <div class="col s8 list-group">
              <div class="s12 l4 list-group-item truncate">
                {{student.rut}}
              </div>
              <div class="s12 l4 list-group-item truncate">
                {{student.user.first_name|title}} {{student.user.last_name|title}}
              </div>
            </div>
            <div style="float:right;">
              <a class="waves-effect waves-light btn btn-danger btn-action"
                href="{% url 'course:delete_student' course_id_char=course.id_char student_rut=student.rut %}">
                <i class="fa fa-trash fa-2x" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </li>
        {% endfor %}
        {% endif %}
      </div>
    </ul>
  </div>
</div>

<!-- Modal Add Student -->
<div id="add_student" class="modal">
  <div class="modal-header">
    <h5 class="modal-title">Agregar estudiantes al curso</h5>
  </div>

  <div id="modal_menu">
    <div class="modal-content row">
      <div class="col s12">
        <a class="col m6 s12 center-align" id="manually">
          <div class="btn-box">
            <h5>Manualmente</h5>
            <i class="fa fa-keyboard-o fa-5x" aria-hidden="true"></i>
          </div>
        </a>
        <a class="col m6 s12 center-align" id="template">
          <div class="btn-box">
            <h5>Plantilla</h5>
            <i class="fa fa-file-text-o fa-5x" aria-hidden="true"></i>
          </div>
        </a>
      </div>
    </div>
    <div class="modal-footer">
      <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
    </div>
  </div>

  <form class="hide" id="form_manually">
    <div class="modal-content center-align">
      <span>Rellene los campos con los datos de los estudiantes.</span>
      <table class="bordered">
        <thead>
          <th>RUT</th>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th></th>
        </thead>
        <tbdoy>
          <div></div>
          <tr>
            <td colspan="4" class="center-align">
              <a id="add" class="btn-floating waves-effect waves-light green"><i class="fa fa-plus fa-4x"></i></a>
            </td>
          </tr>
        </tbdoy>
      </table>
    </div>
    <div class="modal-footer">
      <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
      <button type="submit" class="btn-flat">
        <span>Guardar estudiantes</span>
        <i class="fa fa-spinner fa-pulse fa-3x fa-fw hide"></i>
      </button>
    </div>
  </form>

  <form class="hide" id="form_template">
    <div class="modal-content row">
      <div class="col s12">
        <a class="col m6 s12 center-align" href="{% url 'course:download_csv' course.id %}">
          <div class="btn-box">
            <h6>Descargar Plantilla</h6>
            <i class="fa fa-arrow-circle-o-down fa-5x" aria-hidden="true"></i>
          </div>
        </a>
        <a class="col m6 s12 center-align">
          <div class="btn-box file-field">
            <h6>Cargar Plantilla</h6>
            <i class="fa fa-arrow-circle-o-down fa-5x fa-rotate-180" aria-hidden="true"></i>
            <input type="file" name="csv_file" accept="application/vnd.ms-excel" required>
          </div>
        </a>
      </div>
      <div class="col s12 file-path-wrapper input-field hide">
        <input class="file-path validate" id="name_file" type="text" placeholder="" disabled>
        <label for="name_file">Archivo seleccionado</label>
      </div>
    </div>
    <div class="modal-footer row">
      <div class="col s12">
        <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
        <button class="btn-flat" type="submit">
          <span>Cargar</span>
          <i class="fa fa-spinner fa-pulse fa-3x fa-fw hide"></i>
        </button>
      </div>
    </div>
  </form>
</div>
<!-- End modal add student-->
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
{% endblock %}