apps/login/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^crear-cuenta$', create_account, name='create_account'),
    url(r'^crear-cuenta/email$', validate_email, name='validate_email'),
]

apps/play/urls.py
from django.conf.urls import url

from apps.play.views import *

urlpatterns = [
    url(r'^$', view_plays, name='index'),
    url(r'^stop$', stop_play, name='stop'), #Only POST
    url(r'^(?P<play_id_char>\w+)/$', show_play, name='show'),
    url(r'^(?P<play_id_char>\w+)/reply/(?P<question_id>\d+)/$', reply_play, name='reply'),
    url(r'^(?P<play_id_char>\w+)/dashboard/$', play_result, name='result'),
    url(r'^(?P<play_id_char>\w+)/download-excel$', download_excel, name='excel'),
]

#(?P<question_id>\d+)/

apps/student/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^student/$', index, name='home'),
]

play/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.views.generic import TemplateView

from apps.login.urls import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include ('apps.login.urls', namespace='login')),
	url(r'^', include ('apps.teacher.urls', namespace='teacher')),
    url(r'^', include ('apps.student.urls', namespace='student')),
    url(r'^curso/', include('apps.course.urls', namespace='course')),
    url(r'^formativa/', include('apps.formative.urls', namespace='formative')),  
    url(r'^pregunta/', include('apps.question.urls', namespace='question')),
    url(r'^play/', include('apps.play.urls', namespace='play'))
]

apps/student/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


#from teacher.models import Formative

# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    rut = models.CharField(unique=True, max_length=15)
    study = models.CharField(max_length=100)
    play = models.ManyToManyField('play.Play', through='Reply')

    class Meta:
        managed = False
        db_table = 'student'        


class Answer(models.Model):    
    answer = models.CharField(max_length=100)
    correct = models.IntegerField()
    date = models.DateTimeField()
    student = models.ForeignKey('Student', models.DO_NOTHING)
    play = models.ForeignKey('play.Play', models.DO_NOTHING)
    question = models.ForeignKey('teacher.Question', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'answer'
        unique_together = (('id',),)        


class Reply(models.Model):
    """docstring for Reply"""
    play = models.ForeignKey('play.Play', models.DO_NOTHING)
    student = models.ForeignKey('Student', models.DO_NOTHING)
    start_reply = models.DateTimeField()
    close_reply = models.DateTimeField()
    is_active = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'reply'
        unique_together = (('play', 'student'),)

    def time_to_finish(self):
        """Use in template for render the time for the close play"""
        return self.close_reply - timezone.now()
        

apps/student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from apps.login.views import student_check
from apps.course.models import Course
from apps.student.models import Student
from apps.play.models import Play
from apps.student.models import Reply
from apps.formative.models import Formative
from apps.teacher.models import Question

# Create your views here.
@login_required
def index(request):    
    if student_check(request.user):
        student = request.user.student
        courses = Course.objects.filter(student=student)        
        active_plays = Play.objects.filter(course__in=courses, is_active=1)        
        closed_plays = Play.objects.filter(course__in=courses, is_active=0).order_by("-close_play")

        return render(request,'student/home.html', {
            'courses': courses,
            'active_plays': active_plays,
            'closed_plays': closed_plays,
            })
    else:
        return redirect('teacher:home')

templates/student/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <!-- import css -->
  <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/mas-play.css' %}">
  {% block extracss %}
  {% endblock %}
  <!-- import js -->
  <script src="{% static 'js/library/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/library/materialize.min.js' %}"></script>
  <script src="{% static 'js/library/js.cookie.js' %}"></script>
  <script src="{% static 'js/library/moment.js' %}"></script>
  <script src="{% static 'js/library/moment-timezone-with-data-2012-2022.js' %}"></script>
  <script src="{% static 'js/library/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/mas-play.js' %}"></script>
  <script src="{% static 'js/student.reply.js' %}"></script>
  {% block extrajs %}
  {% endblock %}

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta charset="utf-8"/>
  <link rel="icon" type="image/png" href="{% static 'img/fama_icono.png' %}">
  <title>{% block title %} FAMA {% endblock %}</title>
</head>
<body>

  {% block header %}
  <header>
    <div class="navbar-fixed row">
      <nav class="top-nav" style="margin-bottom: 20px;">
        <div class="container">
          <div class="nav-wrapper">
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="fa fa-bars fa-2x"></i></a>
            <a id="page-title" class="brand-logo">{% block page-title %}{% endblock %}</a>
            {% if reply.close_reply %}
            <ul class="countdown">
              <li id="timer" data-limit-time="{{ reply.time_to_finish }}"></li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
    <ul id="nav-mobile" class="side-nav fixed">
      <div class="center-align">
        <div style="width: 100%; height: 100px; background-color: white"></div>
      </div>
      <div class="center-align">
        {{ user.first_name|title }}&nbsp;{{ user.last_name|title }}
      </div>
      <li><div class="divider"></div></li>
      <li class="bold">
        <a href="{% url 'login:login' %}" class="waves-effect waves-teal"><i class="fa fa-home fa-lg"></i>Inicio</a>
      </li>
      <li><div class="divider"></div></li>
      <li class="bold">
        <a href="{% url 'login:logout' %}" class="waves-effect waves-teal"><i class="fa fa-sign-out fa-lg"></i>Salir</a>
      </li>
      <li class="bold hide">
        <a href="" class="waves-effect waves-teal"><i class="fa fa-cog fa-lg"></i>Configurar Cuenta</a>
      </li>
    </ul>
  </header>
  {% endblock %}

  <main>
  {% block content %}
  {% endblock %}
  </main>

  {% block footer %}
  {% endblock %}

  {% block js %}
  {% endblock %}

</body>
</html>

templates/student/home.html
{% extends 'student/base.html' %}
{% load staticfiles %}

{% block extracss%}
{% endblock %}

{% block extrajs%}
{% endblock %}

{% block title %}
FAMA
{% endblock %}

{% block page-title %}
Mis Evaluaciones
{% endblock %}

{% block content %}
{% if active_plays %}
<div class="row last-row">
  <div class="col s12">
    <ul class="collection with-header">
      <li class="collection-header col s12">
        <div class="left-align col s12">
          <h5>Disponibles</h5>
        </div>
      </li>
      {% for play in active_plays %}
      <li class="collection-item col s12">
        <div class="s12">
          <div class="col s9 list-group">
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;{{play.formative.name}}
            </div>
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-users" aria-hidden="true"></i>&nbsp;{{play.course.code}} - {{play.course.name}}
            </div>
          </div>
          <div class="col s3 right-align">
            <a class="waves-effect waves-light btn s12 right" href="{% url 'play:show' play.id_char %}">
              Comenzar
            </a>
          </div>
        </div>
        <div class="col s12 l4 list-group-item">
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;{{ play.duration_to_time }}
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% else %}
<div class="row last-row">
  <div class="col s12">
    <ul class="collection with-header">
      <li class="collection-header col s12">
        <div class="left-align col s12">
          <h5>Sin evaluaciones disponibles</h5>
        </div>
      </li>
    </ul>
  </div>
</div>
{% endif %}
<!--
{% if closed_plays %}
<div class="row">
  <div class="col s12">
    <ul class="collection with-header">
      <li class="collection-header col s12">
        <div class="left-align col s12">
          <h5>Terminadas</h5>
        </div>
      </li>
      {% for play in closed_plays %}
      <li class="collection-item col s12">
        <div class="s12">
          <div class="col s9 list-group">
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;{{play.formative.name}}
            </div>
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-users" aria-hidden="true"></i>&nbsp;{{play.course.code}} - {{play.course.name}}
            </div>
          </div>
          <div class="col s3 right-align hide">
            <div class="waves-effect waves-teal btn btn-action">
              <i class="fa fa-bar-chart fa-2x" aria-hidden="true"></i>
            </div>
          </div>
        </div>
        <div class="col s4 m4 l4 list-group-item">
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;{{ play.duration_to_time }}
        </div>
        <div class="col s8 m4 l4 list-group-item">
          <i class="fa fa-calendar-times-o" aria-hidden="true"></i>&nbsp;{{ play.close_play|date:"D d/M/Y" }}
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endif %}-->
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
{% endblock %}