apps/course/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', view_courses, name='index'),
    url(r'^nuevo/$', create_course, name='create'),
    url(r'^all$', get_courses, name='all'), #only POST
    url(r'^(?P<course_id_char>\w+)/$', show_course, name='show'),
    url(r'^(?P<course_id_char>\w+)/agregar-estudiantes$', add_students, name='add_students'), #Only POST
    url(r'^(?P<course_id>\d+)/download-template$', download_template, name='download_csv'),
    url(r'^editar/(?P<course_id_char>\w+)/$', edit_course, name='edit'),
    url(r'^borrar/(?P<course_id_char>\w+)$', delete_course, name='delete'),
    url(r'^borrar_estudiante/(?P<course_id_char>\w+)/(?P<student_rut>[\w-]+)$', delete_student, name='delete_student')
]

apps/login/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^crear-cuenta$', create_account, name='create_account'),
    url(r'^crear-cuenta/email$', validate_email, name='validate_email'),
]

apps/play/urls.py
from django.conf.urls import url

from apps.play.views import *

urlpatterns = [
    url(r'^$', view_plays, name='index'),
    url(r'^stop$', stop_play, name='stop'), #Only POST
    url(r'^(?P<play_id_char>\w+)/$', show_play, name='show'),
    url(r'^(?P<play_id_char>\w+)/reply/(?P<question_id>\d+)/$', reply_play, name='reply'),
    url(r'^(?P<play_id_char>\w+)/dashboard/$', play_result, name='result'),
    url(r'^(?P<play_id_char>\w+)/download-excel$', download_excel, name='excel'),
]

#(?P<question_id>\d+)/

apps/question/urls.py
from django.conf.urls import url

from apps.question.views import *

urlpatterns = [    
    url(r'nueva/choice', create_choice, name='create_choice'),
    url(r'nueva/order', create_order, name='create_order'),
    url(r'nueva/inline', create_inlinechoice, name='create_inlinechoice'),
    url(r'nueva/entry', create_textentry, name='create_textentry'),
    url(r'nueva/slider', create_slider, name='create_slider'),
    url(r'nueva/associate', create_associate, name='create_associate'),
    url(r'editar/(?P<question_id>\d+)$', edit_choice, name='edit_choice'),
]

apps/teacher/urls.py
from django.conf.urls import url

from apps.teacher.views import *

urlpatterns = [
    url(r'^principal/$', index, name='home'),
    url(r'^agregar-pregunta$', add_question, name='add_question'),
    url(r'^mis-preguntas/$', view_questions, name='questions'),
    url(r'^mis-preguntas/share/(?P<question_id>\d+)$', share_question),
    url(r'^mis-preguntas/download$', download_question),
    url(r'^mis-preguntas/download/(?P<question_id>\d+)$', download_question),
    url(r'^mis-preguntas/delete$', delete_question),
    url(r'^mis-preguntas/delete/(?P<question_id>\d+)$', delete_question),
    url(r'^delete-folder$', delete_folder),    
]

play/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.views.generic import TemplateView

from apps.login.urls import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include ('apps.login.urls', namespace='login')),
	url(r'^', include ('apps.teacher.urls', namespace='teacher')),
    url(r'^', include ('apps.student.urls', namespace='student')),
    url(r'^curso/', include('apps.course.urls', namespace='course')),
    url(r'^formativa/', include('apps.formative.urls', namespace='formative')),  
    url(r'^pregunta/', include('apps.question.urls', namespace='question')),
    url(r'^play/', include('apps.play.urls', namespace='play'))
]

apps/question/models.py
from django.db import models

# Create your models here.

class Question(models.Model):    
    title = models.CharField(max_length=30, blank=True)
    type = models.CharField(max_length=40)
    spanish_type = models.CharField(max_length=50)
    correct = models.CharField(max_length=100)
    creation_date = models.DateTimeField() 
    share = models.IntegerField()
    code = models.CharField(max_length=9, blank=True)
    url = models.CharField(max_length=40)
    extension = models.CharField(max_length=10)

    #def __str__(self):
     #   return '{}'.format(self.title)

    class Meta:
        managed = False
        db_table = 'question'
        ordering = ('-creation_date',)

apps/teacher/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Teacher(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    question = models.ManyToManyField('Question', through='TeacherHasQuestion')

    class Meta:
        managed = False
        db_table = 'teacher'


class Question(models.Model):    
    title = models.CharField(max_length=30, blank=True)
    type = models.CharField(max_length=40)
    spanish_type = models.CharField(max_length=50)
    correct = models.CharField(max_length=100)
    creation_date = models.DateTimeField() 
    share = models.IntegerField()
    code = models.CharField(max_length=9, blank=True)
    url = models.CharField(max_length=40)
    extension = models.CharField(max_length=10)

    #def __str__(self):
     #   return '{}'.format(self.title)

    class Meta:
        managed = False
        db_table = 'question'
        ordering = ('-creation_date',)


class TeacherHasQuestion(models.Model):
    teacher = models.ForeignKey('Teacher', models.DO_NOTHING)  # Field name made lowercase.
    question = models.ForeignKey('Question', models.DO_NOTHING)  # Field name made lowercase.
    incorporation_date = models.DateTimeField()
    deleted = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'teacher_has_question'
        unique_together = (('teacher', 'question'),)
        ordering = ('-incorporation_date',)

apps/question/views.py
from __future__ import unicode_literals
from django.utils.encoding import smart_text
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.utils import timezone

from play.settings import BASE_DIR
from io import BytesIO
from PIL import Image
import os, zlib, base64, zipfile, shutil
from apps.teacher.models import Teacher, Question, TeacherHasQuestion
import apps.question.manageXML as manageXML


@login_required
def create_choice(request):
    """Create simple choice interaction."""
    if request.method == "GET":
        return render(request, 'question/create_choice.html')
    else:
        if request.POST.get("extension", "") == "zip":
            response = save_zip(request, "Alternativas")
        else:
            response = save_question(request, "Alternativas")

        return JsonResponse(response)

@login_required
def create_order(request):
    """Create simple order interaction."""
    if request.method == "GET":
        return render(request, 'question/create_order.html')
    else:
        if request.POST.get("extension", "") == "zip":
            response = save_zip(request, "Selección ordenamiento")
        else:
            response = save_question(request, "Selección ordenamiento")

        return JsonResponse(response)

@login_required
def create_inlinechoice(request):
    """Create simple inline choice interaction."""
    if request.method == "GET":
        return render(request, 'question/create_inlinechoice.html')
    else:
        if request.POST.get("extension", "") == "zip":
            response = save_zip(request, "Selección entre lineas")
        else:
            response = save_question(request, "Selección entre lineas")

        return JsonResponse(response)

@login_required
def create_textentry(request):
    """Create simple textentry interaction."""
    if request.method == "GET":
        return render(request, 'question/create_textentry.html')
    else:
        if request.POST.get("extension", "") == "zip":
            response = save_zip(request, "Completar texto")
        else:
            response = save_question(request, "Completar texto")

        return JsonResponse(response)

@login_required
def create_slider(request):
    """Create simple slider interaction."""
    if request.method == "GET":
        return render(request, 'question/create_slider.html')
    else:
        if request.POST.get("extension", "") == "zip":
            response = save_zip(request, "Deslizador")
        else:
            response = save_question(request, "Deslizador")

        return JsonResponse(response)

@login_required
def create_associate(request):
    """Create simple associate interaction."""
    if request.method == "GET":
        return render(request, 'question/create_associate.html')
    else:
        if request.POST.get("extension", "") == "zip":
            response = save_zip(request, "Términos pareados")
        else:
            response = save_question(request, "Términos pareados")

        return JsonResponse(response)

@login_required
def edit_choice(request, question_id):
    """Edit simple choice interaction."""
    #questions = []
    if request.method == "GET":
        question = Question.objects.get(id = question_id)
        if (question.type == "choice"):
            q_question = manageXML.data_choice(question.code, question.extension)
            #questions.append({"question": q_question, "data": question})
            return render(request, 'question/edit_choice.html',{'questions': q_question})
        if (question.type == "order"):
            q_question = manageXML.data_order(question.code, question.extension)
            #questions.append({"question": q_question, "data": question})
            return render(request, 'question/edit_order.html',{'questions': q_question})
        if (question.type == "inline"):
            q_question = manageXML.data_inline(question.code, question.extension)
            #questions.append({"question": q_question, "data": question})
            return render(request, 'question/edit_inlinechoice.html',{'questions': q_question})
        if (question.type == "entry"):
            q_question = manageXML.data_entry(question.code, question.extension)
            #questions.append({"question": q_question, "data": question})
            return render(request, 'question/edit_textentry.html',{'questions': q_question})
        if (question.type == "slider"):
            q_question = manageXML.data_slider(question.code, question.extension)
            #questions.append({"question": q_question, "data": question})
            return render(request, 'question/edit_slider.html',{'questions': q_question})
        if (question.type == "associate"):
            q_question = manageXML.data_associate(question.code, question.extension)
            #questions.append({"question": q_question, "data": question})
            return render(request, 'question/edit_associate.html',{'questions': q_question})
    else:
        if request.POST.get("extension", "") == "zip":
            question = Question.objects.get(id = question_id)
            if (question.type == "choice"):
                response = editSave_zip(request, "Alternativas",question_id)
            if (question.type == "order"):
                response = editSave_zip(request, "Selección ordenamiento",question_id)
            if (question.type == "inline"):
                response = editSave_zip(request, "Completar texto",question_id)
            if (question.type == "entry"):
                response = editSave_zip(request, "Texto entre líneas",question_id)
            if (question.type == "slider"):
                response = editSave_zip(request, "Deslizador",question_id)
            if (question.type == "associate"):
                response = editSave_zip(request, "Términos pareados",question_id)
        else:
            question = Question.objects.get(id = question_id)
            if (question.type == "choice"):
                response = editSave_question(request, "Alternativas",question_id)
            if (question.type == "order"):
                response = editSave_question(request, "Selección ordenamiento",question_id)
            if (question.type == "inline"):
                response = editSave_question(request, "Completar texto",question_id)
            if (question.type == "entry"):
                response = editSave_question(request, "Texto entre líneas",question_id)
            if (question.type == "slider"):
                response = editSave_question(request, "Deslizador",question_id)
            if (question.type == "associate"):
                response = editSave_question(request, "Términos pareados",question_id)
        return JsonResponse(response)
        

def editSave_question(request, spanish_type, question_id):
    """Save xml for interaction without image."""
    question_xml = request.POST.get("question", "")
    title = request.POST.get("title", "")
    correct = request.POST.get("correct", "")
    random = request.POST.get("number", "")
    type_question = request.POST.get("type", "")
    extension = request.POST.get("extension", "")

    response = {}
    try:
        q_code = Question.objects.get(id=question_id)
        code = q_code.code
        
        question_url = "preguntas/{0}.{1}".format(code, extension)
        #question.save()

        question = Question.objects.filter(id=question_id).update(
            title=title,
            type=type_question,
            spanish_type=spanish_type,
            correct="alternativa{0}".format(correct),
            creation_date=timezone.now(),
            share=0,
            code=code,
            url=question_url,
            extension=extension)

        file = open(BASE_DIR+"/"+question_url, "w")
        file.write(question_xml)
        file.close()    

        response["result"] = "success"
        return response
    except Exception as e:
        print("Error: {0}".format(e))
        response["result"] = "Error: {0}".format(e)
        return response

def save_question(request, spanish_type):
    """Save xml for interaction without image."""
    question_xml = request.POST.get("question", "")
    title = request.POST.get("title", "")
    correct = request.POST.get("correct", "")
    random = request.POST.get("number", "")
    type_question = request.POST.get("type", "")
    extension = request.POST.get("extension", "")

    response = {}
    try:
        question = Question.objects.create(
            title=title,
            type=type_question,
            spanish_type=spanish_type,
            correct="alternativa{0}".format(correct),
            creation_date=timezone.now(),
            share=0,
            extension=extension)

        code = str(hex(zlib.crc32(bytes(question.id))))[2:]
        question.code = code
        question.url = "preguntas/{0}.{1}".format(code, extension)
        question.save()

        thq = TeacherHasQuestion.objects.create(
            teacher=request.user.teacher, 
            question=question,
            incorporation_date=timezone.now(),
            deleted=0)

        file = open(BASE_DIR+"/"+question.url, "w")
        file.write(question_xml)
        file.close()    

        response["result"] = "success"
        return response
    except Exception as e:
        print("Error: {0}".format(e))
        response["result"] = "Error: {0}".format(e)
        return response


def save_zip(request, spanish_type):
    """Create folder with imsmanifest and interaction.
    Only work with folder, not create the zip file."""
    question_xml = request.POST.get("question", "")
    imsmanifest_xml = request.POST.get("imsmanifest", "")
    title = request.POST.get("title", "")
    correct = request.POST.get("correct", "")
    random = request.POST.get("number", "")
    type_question = request.POST.get("type", "")
    extension = request.POST.get("extension", "")

templates/teacher/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- import css -->
  <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/mas-play.css' %}">
  {% block extracss %}
  {% endblock %}
  <!-- import js -->
  <script type="text/javascript" src="{% static 'js/library/jquery-3.1.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/library/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mas-play.js' %}"></script>
  {% block extrajs %}
  {% endblock %}

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="{% static 'img/fama_icono.png' %}">
  <title>{% block title %} FAMA {% endblock %}</title>
</head>

<body>

  {% block header %}
  <header>
    <div class="navbar-fixed row">
      <nav class="top-nav" style="margin-bottom: 20px;">
        <div class="container">
          <div class="nav-wrapper">
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="fa fa-bars fa-2x"></i></a>
            <a id="page-title" class="brand-logo">{% block page-title %}{% endblock %}</a>
          </div>
        </div>
      </nav>
    </div>
    <ul id="nav-mobile" class="side-nav fixed">
      <div class="center-align">
        <div style="width: 100%; height: 100px; background-color: #ffffff;"></div>
        Hola {{ user.first_name }}
      </div>
      <li>
        <div class="divider"></div>
      </li>
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
          <li class="bold">
            <a href="{% url 'login:login' %}" class="collapsible-header">
              <i class="fa fa-home fa-lg"></i>Inicio
            </a>
          </li>
        </ul>
        <ul class="collapsible collapsible-accordion">
          <li class="bold"><a class="collapsible-header waves-effect waves-teal">Mis Cursos</a>
            <div class="collapsible-body">
              <ul>
                <li id="list_courses"><a href="{% url 'course:index' %}"><i class="fa fa-list-ul"></i>Lista de
                    Cursos</a></li>
                <li id="new_course"><a href="{% url 'course:create' %}"><i class="fa fa-plus"></i>Nuevo Curso</a></li>
              </ul>
            </div>
          </li>
          <li class="bold"><a class="collapsible-header waves-effect waves-teal">Mis Evaluaciones</a>
            <div class="collapsible-body">
              <ul>
                <li id="list_formatives"><a href="{% url 'formative:index' %}"><i class="fa fa-list-ul"></i>Todas</a>
                </li>
                <li id="list_plays"><a href="{% url 'play:index' %}"><i
                      class="fa fa-calendar-times-o"></i>Terminadas</a></li>
                <li id="new_formative"><a href="{% url 'formative:create' %}"><i class="fa fa-plus"></i>Nueva
                    Evaluación</a></li>
              </ul>
            </div>
          </li>
          <li class="bold">
            <a class="collapsible-header" href="{% url 'teacher:questions' %}">Mis Preguntas</a>
            <div class="collapsible-body">
              <ul>
                <li id="list_questions"><a href="{% url 'teacher:questions' %}"><i
                      class="fa fa-list-ul"></i>Almacenadas</a></li>
              </ul>
            </div>
          </li>
          <li class="bold"><a class="collapsible-header waves-effect waves-teal">Crear Pregunta</a>
            <div class="collapsible-body">
              <ul>
                <!--<i class="fa fa-crosshairs" aria-hidden="true"></i>-->
                <li id="simple_choice"><a href="{% url 'question:create_choice' %}">Alternativas</a></li>
                <li id="order"><a href="{% url 'question:create_order' %}">Ordenamiento</a></li>
                <li id="inline"><a href="{% url 'question:create_inlinechoice' %}">Selección entre líneas</a></li>
                <li id="text_entry"><a href="{% url 'question:create_textentry' %}">Completar texto</a></li>
                <li id="slider"><a href="{% url 'question:create_slider' %}">Deslizador</a></li>
                <li id="associate"><a href="{% url 'question:create_associate' %}">Términos pareados</a></li>
              </ul>
            </div>
          </li>
        </ul>
      </li>
      <li>
        <div class="divider"></div>
      </li>
      <li class="bold">
        <a href="{% url 'login:logout' %}" class="waves-effect waves-teal"><i class="fa fa-sign-out fa-lg"></i>Salir</a>
      </li>
      <!--<li class="bold">
        <a href="" class="waves-effect waves-teal"><i class="fa fa-cog fa-lg"></i>Configurar Cuenta</a>
      </li> -->
    </ul>
  </header>
  {% endblock %}

  <main>
    {% block content %}
    {% endblock %}
  </main>

  {% block footer %}
  {% endblock %}

  {% block js %}
  {% endblock %}

</body>

</html>

templates/teacher/home.html
{% extends 'teacher/base.html' %}
{% load staticfiles %}

{% block extracss%}
{% endblock %}

{% block extrajs%}
<script src="{% static 'js/library/js.cookie.js' %}"></script>
<script src="{% static 'js/library/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/library/channels.websocketbridge.js' %}"></script>
<script src="{% static 'js/functions.start_formative.js' %}"></script>
<script src="{% static 'js/functions.stop_formative.js' %}"></script>
<script src="{% static 'js/teacher.home.js' %}"></script>
{% endblock %}

{% block title %}
FAMA - Formative Assessment using Mobile Accessory
{% endblock %}

{% block page-title %}
FAMA
{% endblock %}

{% block content %}
{% if active_plays %}
<div class="row last-row">
  <div class="col s12">
    <ul class="collection with-header">
      <li class="collection-header col s12">
        <div class="left-align col s12">
          <h5>Evaluaciones en curso</h5>
        </div>
      </li>
      {% for play in active_plays %}
      <li class="collection-item col s12">
        <div class="s12">
          <div class="col s6 m8 list-group">
            <div class="s12 list-group-item truncate">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;{{play.formative.name}}
            </div>
            <div class="s12 list-group-item truncate">
              <i class="fa fa-users" aria-hidden="true"></i>&nbsp;{{play.course.code}} - {{play.course.name}}
            </div>
            <div class="s12 list-group-item">
              <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;{{ play.duration_to_time }}
            </div>
          </div>
          <div class="col s6 m4 right-align">
            <div class="waves-effect waves-ligth btn btn-danger btn-action stop-formative"
              data-url="{% url 'play:stop' %}" data-play-id="{{play.id}}">
              <i class="fa fa-stop fa-2x" aria-hidden="true"></i>
            </div>
            <a class="waves-effect waves-light btn btn-action" href="{% url 'play:result' play.id_char %}">
              <i class="fa fa-bar-chart fa-2x" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endif %}

{% if closed_plays %}
<div class="row last-row">
  <div class="col s12">
    <ul class="collection with-header">
      <li class="collection-header valign-wrapper">
        <div class="left-align col s10">
          <h5>Evaluaciones finalizadas</h5>
        </div>
        <div class="valign right-align col s2">
          <a href="{% url 'play:index' %}">
            <i class="fa fa-list fa-2x" style="color: #000000"></i>
          </a>
        </div>
      </li>
      {% for play in closed_plays %}
      <li class="collection-item col s12">
        <div class="s12">
          <div class="col s9 list-group">
            <div class="s12 l4 list-group-item truncate">
              <!-- fa fa-file-o -->
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;{{play.formative.name}}
            </div>
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-users" aria-hidden="true"></i>&nbsp;{{play.course.code}} - {{play.course.name}}
            </div>
          </div>
          <div class="col s3 right-align">
            <a class="waves-effect waves-light btn btn-action" href="{% url 'play:result' play.id_char %}">
              <i class="fa fa-bar-chart fa-2x" aria-hidden="true"></i>
            </a>
            <a class="waves-effect green btn btn-action" href="{% url 'play:excel' play.id_char %}">
              <i class="fa fa-file-excel-o fa-2x" aria-hidden="true"></i>
            </a>
          </div>
        </div>
        <div class="col s4 m4 list-group-item">
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;{{ play.duration_to_time }}
        </div>
        <div class="col s8 m4 list-group-item">
          <i class="fa fa-calendar-times-o" aria-hidden="true"></i>&nbsp;{{ play.close_play|date:"D d/M/Y" }}
        </div>
      </li>
      {% endfor %}

    </ul>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="col s12 m6 l6">
    <ul class="collection with-header">
      <li class="collection-header valign-wrapper">
        <div class="left-align col s8">
          <h5>Mis Evaluaciones</h5>
        </div>
        <div class="valign right-align col s4">
          <a href="{% url 'formative:index' %}" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Ver todas">
            <i class="fa fa-list fa-2x" style="color: #000000"></i>
          </a>
          <a href="{% url 'formative:create' %}" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Nueva">
            <i class="fa fa-plus-square fa-2x" style="padding-left: 10px; color: #000000;"></i>
          </a>
        </div>
      </li>
      {% if formatives %}
      <li class="collection-item center-align col s12">
        <b>&Uacute;ltimas evaluaciones creadas</b>
      </li>
      {% for formative in formatives %}
      <li class="collection-item col s12">
        <div class="s12">
          <div class="col s9 list-group">
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;{{formative.name}}
            </div>
            <div class="s12 l4 list-group-item truncate">
              &nbsp;{{formative.description}}
            </div>
          </div>
          <div class="col s3 right-align">
            <a class="waves-effect waves-light btn btn-action start-formative" data-url="{% url 'course:all' %}"
              data-formative-id={{formative.id}} data-formative-name="{{formative.name}}">
              <i class="fa fa-play fa-2x" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </li>
      {% endfor %}
      <li class="collection-item center-align col s12">
        <b>Actualmente posee {{total_formatives}} evaluaciones</b>
      </li>
      {% else %}
      <a class="collection-item center-align col s12" href="{% url 'formative:create' %}">
        <b>Crear primera evaluación</b>
      </a>
      {% endif %}
    </ul>
  </div>

  <div class="col s12 m6 l6">
    <ul class="collection with-header">
      <li class="collection-header valign-wrapper">
        <div class="left-align col s8">
          <h5>Mis Cursos</h5>
        </div>
        <div class="valign right-align col s4">
          <a href="{% url 'course:index' %}" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Ver todos">
            <i class="fa fa-list fa-2x black-text"></i>
          </a>
          <a href="{% url 'course:create' %}" class="tooltipped" data-position="left" data-delay="50"
            data-tooltip="Nuevo">
            <i class="fa fa-plus-square fa-2x black-text" style="padding-left: 10px;"></i>
          </a>
        </div>
      </li>
      {% if courses %}
      <li class="collection-item center-align col s12">
        <b>&Uacute;ltimos cursos creados</b>
      </li>
      {% for course in courses %}
      <a class="collection-item col s12" href="{% url 'course:show' course.id_char %}">
        <div class="s12">
          <div class="col s12 list-group">
            <div class="s12 l4 list-group-item truncate">
              <i class="fa fa-users" aria-hidden="true"></i>&nbsp;{{course.code}}
            </div>
            <div class="s12 l4 list-group-item truncate">
              &nbsp;{{course.name}}
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
      <li class="collection-item center-align col s12">
        <b>Actualmente posee {{total_course}} cursos</b>
      </li>
      {% else %}
      <a class="collection-item center-align col s12" href="{% url 'course:create' %}">
        <b>Crear primer curso</b>
      </a>
      {% endif %}
    </ul>
  </div>

</div>

{% include "functions/modal_stop_formative.html" %}

{% include "functions/modal_start_formative.html" %}

{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
{% endblock %}