apps/formative/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', view_formatives, name='index'),
    url(r'^nuevo/$', create_formative, name='create'),
    url(r'^play$', start_formative, name='start'), #only POST
    url(r'^editar/(?P<formative_id>\d+)$', edit_formative, name='edit'),
    url(r'^(?P<formative_id>\d+)$', show_formative, name='show'),
    url(r'^borrar/(?P<formative_id>\d+)$', delete_formative, name='delete'),
]

play/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.views.generic import TemplateView

from apps.login.urls import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include ('apps.login.urls', namespace='login')),
	url(r'^', include ('apps.teacher.urls', namespace='teacher')),
    url(r'^', include ('apps.student.urls', namespace='student')),
    url(r'^curso/', include('apps.course.urls', namespace='course')),
    url(r'^formativa/', include('apps.formative.urls', namespace='formative')),  
    url(r'^pregunta/', include('apps.question.urls', namespace='question')),
    url(r'^play/', include('apps.play.urls', namespace='play'))
]

apps/formative/models.py
from django.db import models

# Create your models here.
class Formative(models.Model):
    #id = models.AutoField()
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200, blank=True)
    creation_date = models.DateTimeField()
    teacher = models.ForeignKey('teacher.Teacher', models.DO_NOTHING)
    course = models.ManyToManyField('course.Course', through='play.Play')
    question = models.ManyToManyField('teacher.Question', through='FormativeHasQuestion')

    class Meta:
        managed = False
        db_table = 'formative'
        unique_together = (('id', 'teacher'),)
        ordering = ('-creation_date',)

    def has(self, question):
        """Verify if question belongs to this formative"""
        return self.question.filter(id=question).exists()


class FormativeHasQuestion(models.Model):
    formative = models.ForeignKey('Formative', models.DO_NOTHING)
    question = models.ForeignKey('teacher.Question', models.DO_NOTHING)
    order = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'formative_has_question'
        unique_together = (('formative', 'question'),)
        ordering = ('order',)

apps/formative/forms.py
from django import forms

from .models import Formative, FormativeHasQuestion

class FormativeForm(forms.ModelForm):
    """docstring for CourseForm"""
    class Meta:
        model = Formative
        fields = ('name', 'description', 'question')
        widgets = {
        	'name': forms.TextInput(attrs={'class':'validate', 'length': 50, 'data-length': 50, 'placeholder': 'Ejemplo: Conceptos básicos'}),
        	'description': forms.Textarea(attrs={'class':'materialize-textarea validate', 'length': 200, 'data-length': 200, 'placeholder': 'Ejemplo: Preguntas sobre los puntos claves de los contenidos vistos durante la semana'}),
            'question': forms.CheckboxSelectMultiple(),
        }

apps/formative/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.utils import timezone
from django.core import serializers
from datetime import timedelta
from django.core.exceptions import ObjectDoesNotExist

from .forms import FormativeForm
from .models import Formative, FormativeHasQuestion
from apps.play.models import Play
from apps.student.models import Student
from apps.teacher.models import Question
from apps.course.models import Course
import apps.question.manageXML as manageXML

@login_required
def view_formatives(request):
    formatives = Formative.objects.filter(teacher=request.user.teacher)
    return render(request, 'formative/index.html', {'formatives': formatives})


@login_required
def show_formative(request, formative_id):
    formative = Formative.objects.get(id=formative_id)
    return render(request, 'formative/show.html', {'formative': formative})


@login_required
def create_formative(request):
    if request.method == "POST":
        formative = Formative.objects.create(
            name=request.POST.getlist('name')[0],
            description=request.POST.getlist('description')[0],
            creation_date=timezone.now(),
            teacher=request.user.teacher)
        position = 0
        for question_id in request.POST.getlist('questions[]'):
            question = Question.objects.get(id=question_id)
            fhasq = FormativeHasQuestion.objects.create(
                order=position,
                formative=formative, 
                question=question)
            fhasq = None
            question = None
            position = position + 1
        data = {}
        data['redirect'] = '/formativa/'
        return JsonResponse(data)
    else:
        data = request.user.teacher.question.all().order_by('teacherhasquestion__incorporation_date').reverse()
        questions = []
        for question in data:
            #print(question.type)
            if question.type == "choice":
                q_question = manageXML.data_choice(question.code, question.extension)["itemBody"]["choiceInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "associate":
                q_question = manageXML.data_associate(question.code, question.extension)["itemBody"]["associateInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "entry":
                q_question = manageXML.data_entry(question.code, question.extension)["itemBody"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "slider":
                q_question = manageXML.data_slider(question.code, question.extension)["itemBody"]["sliderInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "order":
                q_question = manageXML.data_order(question.code, question.extension)["itemBody"]["orderInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "inline":
                q_question = manageXML.data_inline(question.code, question.extension)["itemBody"]["question"]
                questions.append({"question": q_question, "data": question})
        form = FormativeForm()
    return render(request, 'formative/create.html', {'form': form, 'questions': questions, 'title': 'Crear Evaluación'})


@login_required
def edit_formative(request, formative_id):
    formative = Formative.objects.get(id=formative_id)
    if request.method == 'GET':
        data_selected = formative.question.all().order_by('formativehasquestion__order')
        data = request.user.teacher.question.exclude(id__in=data_selected).order_by('teacherhasquestion__incorporation_date').reverse()
        questions = []
        for question in data:
            #print(question)
            if question.type == "choice":
                q_question = manageXML.data_choice(question.code, question.extension)["itemBody"]["choiceInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "associate":
                q_question = manageXML.data_associate(question.code, question.extension)["itemBody"]["associateInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "entry":
                q_question = manageXML.data_entry(question.code, question.extension)["itemBody"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "slider":
                q_question = manageXML.data_slider(question.code, question.extension)["itemBody"]["sliderInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "order":
                q_question = manageXML.data_order(question.code, question.extension)["itemBody"]["orderInteraction"]["question"]
                questions.append({"question": q_question, "data": question})
            if question.type == "inline":
                q_question = manageXML.data_inline(question.code, question.extension)["itemBody"]["question"]
                questions.append({"question": q_question, "data": question})
        question_selected = []
        for question in data_selected:
            if question.type == "choice":
                q_question = manageXML.data_choice(question.code, question.extension)["itemBody"]["choiceInteraction"]["question"]
                question_selected.append({"question": q_question, "data": question})
            if question.type == "associate":
                q_question = manageXML.data_associate(question.code, question.extension)["itemBody"]["associateInteraction"]["question"]
                question_selected.append({"question": q_question, "data": question})
            if question.type == "entry":
                q_question = manageXML.data_entry(question.code, question.extension)["itemBody"]["question"]
                question_selected.append({"question": q_question, "data": question})
            if question.type == "slider":
                q_question = manageXML.data_slider(question.code, question.extension)["itemBody"]["sliderInteraction"]["question"]
                question_selected.append({"question": q_question, "data": question})
            if question.type == "order":
                q_question = manageXML.data_order(question.code, question.extension)["itemBody"]["orderInteraction"]["question"]
                question_selected.append({"question": q_question, "data": question})
            if question.type == "inline":
                q_question = manageXML.data_inline(question.code, question.extension)["itemBody"]["question"]
                question_selected.append({"question": q_question, "data": question})
        form = FormativeForm(instance=formative)
    else:
        formative.name = request.POST.getlist('name')[0]
        formative.description=request.POST.getlist('description')[0]
        formative.creation_date=timezone.now()
        formative.question.clear()

        position = 0
        for question_id in request.POST.getlist('questions[]'):
            question = Question.objects.get(id=question_id)
            fhasq = FormativeHasQuestion.objects.create(
                order=position,
                formative=formative, 
                question=question)
            fhasq = None
            question = None
            position = position + 1

        formative.save()
        data = {}
        data['redirect'] = '/formativa/'
        return JsonResponse(data)
    return render(request, 'formative/create.html', {'form': form, 'questions': questions, 'question_selected': question_selected, 'title': 'MAs Play - Editar Evaluación'})


@login_required
def start_formative(request):
    if request.method == "POST":
        formative = Formative.objects.get(id=request.POST['formative'])
        course = Course.objects.get(id=request.POST['course'])
        duration = request.POST['time']

        play_obj = Play.objects.all()
        #print(len(play_obj))
        if(len(play_obj) > 0 ):
            max_id = Play.objects.latest('id').id
        else:
            max_id = 0
        max_id = max_id + 1

        try:
            play = Play.objects.create(
                id_char="P{0}C{1}F{2}".format(max_id, course.id, formative.id),
                creation_play=timezone.now(),
                duration=timedelta(minutes=int(duration)),
                start_play=timezone.now(),
                limit_time=timedelta(hours=1),
                close_play=timezone.now() + timedelta(hours=1),
                is_active=1,
                formative=formative,
                course=course)

            play.id_char = "P{0}{1}".format(                    
                play.id,
                play.id_char)
            play.save()            
            data = {"redirect": "OK"}

        except Exception as e:
            print("Error: ", e)
            data = {"message": "Error: {0}".format(e)}

    return JsonResponse(data)


@login_required
def delete_formative(request, formative_id):
  formatives = Formative.objects.filter(teacher=request.user.teacher)
  try:
    formative = Formative.objects.get(id=formative_id)
    formative.delete()
    return render(request, 'formative/index.html', {'formatives': formatives})
  except Exception as e:
    print(e)
    messages.add_message(request, messages.ERROR, str("No se puede eliminar la evaluación porque tiene preguntas asociadas."))
    return render(request, 'formative/index.html', {'formatives': formatives})

templates/formative/create.html
{% extends 'teacher/base.html' %}
{%load staticfiles %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'css/formative.create.css' %}">
<style type="text/css">
  .card-panel {
    padding: 10px !important;
  }

  .collection {
    overflow: initial;
  }

  .collection-item {
    cursor: move;
  }
</style>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/library/js.cookie.js' %}"></script>
<script src="{% static 'js/library/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/library/jquery.ui.touch-punch.min.js' %}"></script>
<script src="{% static 'js/formative.create.js' %}"></script>
{% endblock %}

{% block title %}
{% if form.name.value != None %}
FAMA - Nueva Evaluación
{% else %}
FAMA - Editar Evaluación
{% endif %}
{% endblock %}

{% block page-title %}
{% if form.name.value != None %}
Editar Evaluación {{ form.name.value }}
{% else %}
Nueva Evaluación
{% endif %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12 m6">
    <ul class="collection">
      <li class="collection-item">
        <form id="form-new-formative" method="POST">
          {% csrf_token %}
          <div class="row last-row">
            <div class="input-field col s12">
              {{ form.name }}
              <label for="{{ form.name.id_for_label }}">Nombre de la evaluación</label>
            </div>
          </div>
          <div class="row last-row">
            <div class="input-field col s12">
              {{ form.description }}
              <label for="{{ form.description.id_for_label }}">Descripción de la evaluación (Opcional)</label>
            </div>
          </div>
          <div class="row last-row">
            <label class="col s12">Preguntas de la evaluación</label>
            <div class="input-field col s12">
              {% if question_selected %}
              <ul id="formative-questions" class="collection connectedSortable">
                {% for question in question_selected %}
                <li class="collection-item" data-id="{{ question.data.id }}">{{ question.question|safe }} -
                  {{ question.data.spanish_type }}</li>
                {% endfor %}
              </ul>
              {% else %}
              <ul class="collection connectedSortable valign-wrapper center-align" id="formative-questions">
                <h5>Arrastre desde la derecha las preguntas que desea asignar en esta evaluación</h5>
              </ul>
              {% endif %}
            </div>
          </div>
          <div class="row last-row">
            <span class="col s12 center-align">* Las preguntas se le mostraran al estudiante en el mismo orden</span>
            <div class="right-align">
              <button class="btn waves-effect waves-light" type="submit">
                Guardar
                <i class="fa fa-send right" aria-hidden="true"></i>
              </button>
            </div>
          </div>
        </form>
      </li>
    </ul>
  </div>

  <div class="col s12 m6">
    <ul class="collection with-header">
      <li class="collection-header">
        <div class="valign-wrapper">
          <div class="center-align col s12">
            <h5>Mis Preguntas</h5>
          </div>
        </div>
      </li>
      <li class="collection-item">
        <div class="input-field">
          <i class="material-icons prefix fa fa-search" aria-hidden="true"></i>
          <input type="text" id="search-input">
          <label for="search-input">Buscar entre mis preguntas</label>
        </div>
        <div>
          {% if questions %}
          <ul class="collection connectedSortable" id="list-question-for-formative">
            {% for question in questions %}
            <li class="collection-item" data-id="{{ question.data.id }}">{{question.data.title|safe}} - {{ question.question|safe }} -
              {{ question.data.spanish_type }}</li>
            {% endfor %}
          </ul>
          {% else %}
          <a href="#">
            <div class="card-panel hoverable teal">
              <span class="white-text">Cree su primera pregunta</span>
            </div>
          </a>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
<script>
  $(document).ready(function () {
    $('#nav-mobile ul.collapsible li#new_formative').addClass('active').parent().parent().show().parent().addClass('active')
  });
</script>
{% endblock %}

templates/formative/index.html
{% extends 'teacher/base.html' %}

{% block extracss %}
<style type="text/css">
  .clickable-row {
    cursor: pointer;
  }
</style>
{% endblock %}

{% block extrajs %}
{% endblock %}

{% block title %}
FAMA - Mis Evaluaciones
{% endblock %}

{% block page-title %}
Mis Evaluaciones
{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12">
    <div style="overflow-x: auto;">
      <table class="bordered card-box">
        <thead>
          <tr>
            <th data-field="name" style="min-width: 150px;">Nombre</th>
            <th data-field="description" style="min-width: 150px;">Descripci&oacute;n</th>
            <th class="center-align" style="width: 80px;" data-field="edit">Acciones</th>
            <th class="center-align" style="width: 100px; min-width: 100px;" data-field="delete">Eliminar</th>
          </tr>
        </thead>
        <tbody>
          {% for formative in formatives %}
          <tr>
            <!--class="clickable-row hoverable" data-href="{% url 'formative:show' formative.id %}"-->
            <td>{{ formative.name }}</td>
            <td>{{ formative.description }}</td>
            <td class="center-align">
              <a class="waves-effect waves-light btn btn-action" href="{% url 'formative:edit' formative.id %}">
                <i class="fa fa-pencil" aria-hidden="true"></i>
              </a>
            </td>

            <td class="center-align">
              <a href="{% url 'formative:delete' formative_id=formative.id %}" class="waves-effect waves-light btn"
                style="background-color:#ee6e73;">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
            </td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
<script>
  $('.modal').modal();
  $(document).ready(function () {
    $("a.btn").parents('td').css("padding-bottom", "0").css("padding-top", "0");
    $('#nav-mobile ul.collapsible li#list_formatives').addClass('active').parent().parent().show().parent().addClass('active')

    $(".clickable-row").click(function () {
      window.location = $(this).data("href");
    });

    {% if messages %}
    {% for message in messages %}
    Materialize.toast('{{message}}', 5000, 'rounded');
    {% endfor %}
    {% endif %}
  });
</script>
{% endblock %}

templates/formative/show.html
{% extends 'teacher/base.html' %}
{%load staticfiles %}

{% block extracss %}
<style type="text/css">
  .modal {
    width: 75% !important;
  }

  .card-panel {
    padding: 10px !important;
  }

  /*div#add_student a#add {
    position: relative;
    top: -28px;
  }*/
</style>
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'js/library/js.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/course.show.js' %}"></script>
{% endblock %}

{% block title %}
FAMA - {{formative.name}}
{% endblock %}

{% block page-title %}
{{formative.name}}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12 m12 l7">
    <ul class="collection with-header">
      <li class="collection-header">
        <div class="row valign-wrapper" style="margin-bottom: 0px">
          <div class="left-align col s6">
            <h5>Evaluaciones</h5>
          </div>
          <div class="valign right-align col s6">
            <a href="#" class="tooltipped" data-position="left" data-delay="50" data-tooltip="Ver todas">
              <i class="fa fa-list fa-2x" style="color: #000000"></i>
            </a>
            <a href="#" class="tooltipped" data-position="left" data-delay="50" data-tooltip="Nueva">
              <i class="fa fa-plus-square fa-2x" style="padding-left: 10px; color: #000000;"></i>
            </a>
          </div>
        </div>
      </li>
      <li class="collection-item center-align">
        <div class="row">
          {% if formatives %}
          {% else %}
          <div clas="col s12 m5">
            <div class="card-panel teal">
              <span class="white-text">Asigne su primera evaluación al curso</span>
            </div>
          </div>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>

  <div class="col s12 m12 l5">
    <ul class="collection with-header">
      <li class="collection-header">
        <div class="row valign-wrapper" style="margin-bottom: 0px">
          <div class="left-align col s6">
            <h5>Estudiantes<h5>
          </div>
          <div class="valign right-align col s6">
            <!--
            <a href="#" class="tooltipped" data-position="left" data-delay="50" data-tooltip="Ver todos">
              <i class="fa fa-list fa-2x" style="color: #000000"></i>
            </a>
            -->
            <a href="#add_student" class="tooltipped" data-position="left" data-delay="50"
              data-tooltip="Agregar estudiantes">
              <i class="fa fa-plus-square fa-2x" style="padding-left: 10px; color: #000000;"></i>
            </a>
          </div>
        </div>
      </li>
      <li class="collection-item center-align">
        <div id="list_students" class="row" style="max-height: 400px; overflow-y: auto;">
          {% if students %}
          <span>Estudiantes inscritos: <span data-count='{{ students.count }}'>{{ students.count }}</span></span>
          {% for student in students %}
          <div class="card-panel hoverable teal col s12">
            <div class="col s10">
              <div class="col s12 white-text left-align">{{student.rut}}</div>
              <div class="col s12 white-text left-align">{{student.first_name|title}} {{student.last_name|title}}</div>
            </div>
            <div class="valign-wrapper col s2">
              <a href="#">
                <i class="fa fa-trash-o fa-2x col s12" style="color: #fff;"></i>
              </a>
            </div>
          </div>
          {% endfor %}
          {% else %}
          <div clas="col s12">
            <a href="#add_student">
              <div class="card-panel teal">
                <span class="white-text">Agrege alumnos al curso</span><br>
              </div>
            </a>
          </div>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
{% endblock %}